### ISSUE TITLE
make test complains about missing MCU header

### ISSUE THREAD

**Issue by voxspox** [contiki-ng/mspsim#42]
Hi

'make test' fails while complaining about unknown MCU. For compilation -mmcu=msp430x1611 is given, but this (generic) cpu type is not listed in msp430.h and leads to the warning.

> make test
> (cd tests && make)
> make[1]: Entering directory `.../src/mspsim/tests'
> msp430-gcc -I. -DWITH_ASCII -Wall -mmcu=msp430x1611 -g -Os -DAUTOSTART_ENABLE -c cputest.c -o cputest.co
> In file included from cputest.c:44:0:
> /usr/lib/gcc/msp430/4.6.3/../../../../msp430/include/msp430.h:813:2: warning: #warning Unable to identify and include MCU header, use -mmcu=MCU [-Wcpp]

using this software:
  mspsim last version from git
  gcc version 4.6.3 20120301 (mspgcc LTS 20120406 unpatched) (GCC) 
  Ubuntu 14.04 LTS

**Comment by voxspox** [comment]
changing MCU to msp430f1611 in tests/Makefile helped in my case.

**Comment by cmorty** [comment]
Can you make a pull-request?
